# Jekyll Config

# Site settings
title: Tanner Krewson
description: Software Engineer Intern at ESPN, Drawphone, Spyout, Connect 4, Lansite, and more
email: tannerkrewson@gmail.com
github_username:  tannerkrewson
linkedin_username: tannerkrewson
facebook_username: tannermkrewson
snapchat_username: tannerkrewson

# Build settings
markdown: kramdown
