# Jekyll Config

# Site settings
title: Tanner Krewson
description: I try to do cool things when I can.
email: tannerkrewson@gmail.com
github_username:  tannerkrewson
linkedin_username: tannerkrewson
facebook_username: tannermkrewson

# Build settings
markdown: kramdown
