# Jekyll Config

# Site settings
title: Tanner Krewson
description: When I have a problem, I write a program to solve it.
email: tannerkrewson@gmail.com
github_username:  tannerkrewson
linkedin_username: tannerkrewson
facebook_username: tannermkrewson

# Build settings
markdown: kramdown
