# Jekyll Config

# Site settings
title: Tanner Krewson
description: Software Engineer Intern at Goldman Sachs, Disney and ESPN. Drawphone, Connect 4, PTSU Exposed...
email: tannerkrewson@gmail.com
github_username:  tannerkrewson
linkedin_username: tannerkrewson
facebook_username: tannermkrewson

# Build settings
markdown: kramdown
